#!/usr/bin/env bash

set -o errexit
set -o nounset

main() {
    echo "WARNING: THIS SCRIPT WILL TRIGGER A COMMIT & PUSH OVER ORIGIN AND HEROKU REMOTES"
    cd public
    npm run build:prod
    cd ..
    cd hastock
    stack build
    stack --local-bin-path ./dist install --ghc-options '-optl-static -fPIC'
    cd ..
    git add .
    git commit -m "DEPLOY"
    git push origin master
    git push heroku master
}

main
